### ISSUE TITLE
Upgrade SQLite and SQLCipher

### ISSUE THREAD

**Issue by someblue** [xeodou/go-sqlcipher#11]
Hi, @xeodou , thanks for your awesome library!

A newer version of SQLite and SQLCipher has been released. Can you upgrade it to latest version? If not, how can I upgrade it?

**Comment by xeodou** [comment]
Sure @someblue I will plan some time to upgrade it.

**Comment by someblue** [comment]
Thanks! Have a nice Spring Festival!

**Comment by someblue** [comment]
Hello, @xeodou , any progress with the upgrade? When are planning to finish?

**Comment by xeodou** [comment]
Hi  @someblue  Sorry for the late.
I just upgrade to the latest version of go-sqlite3 and sqlcipher. But be aware of the API change, pleae take a look at the simple infrusctuction to upgrade from old version
https://github.com/xeodou/go-sqlcipher#upgrade

**Comment by someblue** [comment]
Thanks very much!!!
