### ISSUE TITLE
cannot find -lcrypto

### ISSUE THREAD

**Issue by tgoding** [xeodou/go-sqlcipher#12]
`PS C:\Windows\system32> go get -v github.com/xeodou/go-sqlcipher
d:/workspace/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcrypto
collect2.exe: error: ld returned 1 exit status`

-----------------

`OpenSSL> version
OpenSSL 1.1.1c  28 May 2019
OpenSSL>`

-----------------
windows10 64

**Comment by xeodou** [comment]
Please read the wiki page here https://github.com/xeodou/go-sqlcipher/wiki/Building#issues . It explains how to help you address the issue.
