### ISSUE TITLE
parameters to open with regular db browser

### ISSUE THREAD

**Issue by eranyanay** [xeodou/go-sqlcipher#17]
What parameters are required to open an encrypted db with sqlite browser?
Neither of the suggested options (Sqlcipher 3.x, 4.x or custom) seems to work
What is the specific AES256 algo, number of iterations, hmac algo and page size to use?

**Comment by xeodou** [comment]
Hi @eranyanay 
It's a feature that sqlite browser should support, right you need to compile the sqlcipher version of SQLite Brower by yourself. If you want to use the application open the encrypted DB. Alternatively, you can use `sqlcipher` command line to query the DB. 
This link may help you.
https://github.com/sqlitebrowser/sqlitebrowser/wiki/SQLCipher:-Build-from-Source-on-Debian-Stretch---Newbie-Instructions
