### ISSUE TITLE
PRAGMA key shall use quotes for key value

### ISSUE THREAD

**Issue by torwald-sergesson** [xeodou/go-sqlcipher#20]
Currently library does not allows to use any symbols except alphanumeric. Although it shall be supported according to SQLCipher documentation: https://www.zetetic.net/sqlcipher/sqlcipher-api/#PRAGMA_key
For instance now it's impossible to use keys like in this example:

```
PRAGMA key = "x'2DD29CA851E7B56E4697B0E1F08507293D761A05CE4D1B628663F411A8086D99'";
```

**Comment by xeodou** [comment]
it's merged. Thanks @torwald-sergesson  for the fix.
