### ISSUE TITLE
sqlite3-binding.c:24328:26: fatal error: openssl/rand.h: No such file or directory

### ISSUE THREAD

**Issue by xlango** [xeodou/go-sqlcipher#22]

**Comment by shishuwu** [comment]
Encounter the same issue. After i change to **mutecomm/go-sqlcipher,** it is ok.

An extra topic:  
After aligning with golang-migrate & mutecomm/go-sqlcipher, it always pops up multiple definitions error
`# github.com/golang-migrate/migrate/v4/database/sqlite3.test
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\ADMINI~1\AppData\Local\Temp\go-link-888637035\000044.o: in function `sqlite3_status64':
C:\Users\Administrator\go\pkg\mod\github.com\mutecomm\go-sqlcipher@v0.0.0-20190227152316-55dbde17881f/sqlite3.c:23092: multiple definition of `sqlite3_status64'; C:\Users\ADMINI~1\AppData\Local\Temp\go-link-888637035\000011.o:C:\Users\Administrator\go\pkg\mod\github.com\mattn\go-sqlite3@v1.10.0/sqlite3-binding.c:20370: first defined here
`

**Comment by xeodou** [comment]
The reason is the library trying to dynamic load the openssl library and seems it's not in the default place. you can read the wiki page here to solve your problem https://github.com/xeodou/go-sqlcipher/wiki/Building#issues
