### ISSUE TITLE
What is its default settings？

### ISSUE THREAD

**Issue by fujiawei-dev** [xeodou/go-sqlcipher#23]
What is its default settings？

```go
sql.Open("sqlite3", "users.db?_key=123456")
```

**Comment by xeodou** [comment]
@fujiawei-dev  Can you add more details for your question?

**Comment by fujiawei-dev** [comment]
> @fujiawei-dev Can you add more details for your question?

Thanks for your reply. I meant its default page size, kdf algorithm etc.

`sql.Open("sqlite3", "users.db?_key=123456")` 

But I already know:

![image](https://user-images.githubusercontent.com/29617572/88519540-dd64eb00-d024-11ea-85eb-0957c430b1c0.png)

**Comment by xeodou** [comment]
Great. Glad you solve it.
