### ISSUE TITLE
error: invalid argument type 'void' to unary expression

### ISSUE THREAD

**Issue by ghost** [xeodou/go-sqlcipher#24]
I am trying to compile `go-sqlcipher` as part of the [hover](https://github.com/go-flutter-desktop/hover) project so that I can create Darwin packages of my app via the [hover docker method](https://github.com/go-flutter-desktop/hover#packaging). I modified the [Dockerfile](https://github.com/go-flutter-desktop/hover/blob/master/Dockerfile) to have OpenSSL installed.

However, as soon as I try to get the build, I get this error:

```
github.com/xeodou/go-sqlcipher
# github.com/xeodou/go-sqlcipher
sqlite3-binding.c:24508:10: error: invalid argument type 'void' to unary expression
sqlite3-binding.c:24511:10: error: invalid argument type 'void' to unary expression
sqlite3-binding.c:24514:10: error: invalid argument type 'void' to unary expression
sqlite3-binding.c:24520:6: error: invalid argument type 'void' to unary expression
sqlite3-binding.c:24522:8: error: invalid argument type 'void' to unary expression
sqlite3-binding.c:24524:6: error: invalid argument type 'void' to unary expression
sqlite3-binding.c:24539:11: warning: implicit declaration of function 'PKCS5_PBKDF2_HMAC' is invalid in C99 [-Wimplicit-function-declaration]
11:53:34 build.go:457: hover: Go build failed: exit status 2
```

My command line is rather long so it is in a tiny shell script:
```bash
#!/bin/bash
docker run \
    --rm \
    --mount type=bind,source=/home/yann/worldr/github/desktop-app,target=/app \
    --mount type=bind,source=/home/yann/.cache/hover/engine,target=/root/.cache/hover/engine \
    --mount type=bind,source=/home/yann/.cache/hover/docker-go-cache,target=/go-cache \
    --env GOCACHE=/go-cache \
    --env HOVER_SAFE_CHOWN_UID=1000 \
    --env HOVER_SAFE_CHOWN_GID=1000 \
    --env GOPROXY=direct \
    --env GOPRIVATE= \
    my-desktop-app-builder \
    hover-safe.sh \
    build \
    --verbose \
    darwin-dmg \
    --skip-flutter-build-bundle \
    --skip-engine-d
```

_Any idea what I am doing wrong?_

**Comment by xeodou** [comment]
@ygworldr  which OpenSSL version do you use?

**Comment by ghost** [comment]
In the end, we managed to get it working via a docker image of MacOS on CircleCI. So, of course, I do not have the dockerfile anymore. I really should have included it, shouldn't I? 

I seem to remember it would have been the latest version… 

Feel free to close this for now. If someone gets the same problem, they can re-open. My apologies.
