### ISSUE TITLE
windows10 error

### ISSUE THREAD

**Issue by sayyoume** [xeodou/go-sqlcipher#27]
![image](https://user-images.githubusercontent.com/3301385/94004383-30fa7780-fdcf-11ea-8eee-7edfa6beecae.png)
I set the environment variable. but when i use
go install   show the error:
![image](https://user-images.githubusercontent.com/3301385/94004924-06f58500-fdd0-11ea-8ef5-abe720f0a69d.png)
How to solve???

**Comment by sayyoume** [comment]
![image](https://user-images.githubusercontent.com/3301385/94005283-a581e600-fdd0-11ea-951a-cbbb26324c39.png)
the environment variable is the openssl lib and include

**Comment by xeodou** [comment]
@sayyoume  plz take a look at this page https://github.com/xeodou/go-sqlcipher/wiki/Building#issues , it's because of the OpenSSL installed in MingW with different lib name.

**Comment by navono** [comment]
Followed the actions in the issue and still got the same error.

**Comment by xeodou** [comment]
> Followed the actions in the issue and still got the same error.

What error do you get? Did you follow the instruction here https://github.com/xeodou/go-sqlcipher/wiki/Building#issues

**Comment by navono** [comment]
Thank you for your response.

Here is my Env:
```
$ gcc --version
gcc.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

OS: Win 10(2004) 64bit
```

Here is the errors:
```
$ go get github.com/xeodou/go-sqlcipher
# github.com/xeodou/go-sqlcipher
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../../x86_64-w64-mingw32/lib/../lib/libcrypto.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../../x86_64-w64-mingw32/lib/../lib\libcrypto.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../../lib/libcrypto.dll.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../../x86_64-w64-mingw32/lib/libcrypto.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../../x86_64-w64-mingw32/lib\libcrypto.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../libcrypto.dll.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../../x86_64-w64-mingw32/lib/../lib/libcrypto.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../../lib/libcrypto.dll.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../../x86_64-w64-mingw32/lib/libcrypto.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../libcrypto.dll.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../../x86_64-w64-mingw32/lib/../lib/libcrypto.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../../lib/libcrypto.dll.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../../x86_64-w64-mingw32/lib/libcrypto.a when searching for -lcrypto
d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible d:/devenv/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../
../../libcrypto.dll.a when searching for -lcrypto
collect2.exe: error: ld returned 1 exit status
# github.com/xeodou/go-sqlcipher
sqlite3-binding.c: In function 'sqlite3SelectNew':
sqlite3-binding.c:130284:10: warning: function may return address of local variable [-Wreturn-local-addr]
130284 |   return pNew;
       |          ^~~~
sqlite3-binding.c:130244:10: note: declared here
130244 |   Select standin;
       |          ^~~~~~~
```
It basically follows that steps, but is slightly different because of the OpenSSL version change. I installed the `1.1.1h` (x86)version. And I copied `lib\MinGW\libcrypto.def` and `lib\MinGW\libcrypto.dll.a` from the OpenSSL installation directory to the `mingw64\x86_64-w64-mingw32\lib` directory, and renamed `libcrypto.dll.a` to `libcrypto.a`; copied the `include` under OpenSSL to `mingw64\x86_64-w64-mingw32\include`.

![lib](https://user-images.githubusercontent.com/3746639/99326809-8aed5a00-28b3-11eb-937a-2850c940b1cb.PNG)

![include](https://user-images.githubusercontent.com/3746639/99326816-8cb71d80-28b3-11eb-9cd1-0ded213bc1ce.PNG)

Did any of the steps go wrong?

**Comment by navono** [comment]
The reason for using OpenSSL 32-bit is that there is no lib file for MingW under OpenSSL 64-bit.

**Comment by navono** [comment]
After put `OpenSSL(64 bit)\lib\libcrypto.def` and `OpenSSL(64 bit)\lib\libcrypto.lib`(rename to `libcrypto.a`) and `include\openssl` to `mingw64` directory, everything works fine.

**Comment by navono** [comment]
I create a demo like this:
```
package sqlite3_demo

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	"github.com/jinzhu/gorm"
	_ "github.com/xeodou/go-sqlcipher"
)

type Product struct {
	gorm.Model
	Code  string
	Price uint
}

func RunDemo() {
	run()
}

func openDB(dbPath, key string) (*gorm.DB, error) {
	db, err := gorm.Open("sqlite3", dbPath)
	if err != nil {
		log.Fatal(err)
		return nil, err
	}

	p := fmt.Sprintf("PRAGMA key = '%s';", key)
	db = db.Exec(p)
	return db, nil
}

func run() {
	dbPath := "./xeodou.db"
	key := "123456"

	db, err := openDB(dbPath, key)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	db.AutoMigrate(&stock{})

	var existS stock
	if db.Model(&stock{}).Where(&stock{
		Symbol: "a",
	}).Find(&existS).RecordNotFound() {
		s := stock{
			Date:   "1",
			Trans:  "b",
			Symbol: "a",
			Qty:    10,
			Price:  0,
		}
		db.Save(&s)
		return
	}

	fmt.Println(existS)
}
```

Generates a db file after the first normal run, opens the db file on the second run with an error:
> file is not a database

**Comment by navono** [comment]
I'm having a strange problem. I was able to get it installed and running on one PC, but on another PC I was experiencing the following error:
```
# github.com/xeodou/go-sqlcipher
C:\Users\PINGQI~1\AppData\Local\Temp\go-build372864814\b056\_x012.o: In function `sqlcipher_openssl_deactivate':
E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24452: undefined reference to `EVP_cleanup'
C:\Users\PINGQI~1\AppData\Local\Temp\go-build372864814\b056\_x012.o: In function `sqlcipher_openssl_activate':
E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24423: undefined reference to `OPENSSL_add_all_algorithms_noconf'
C:\Users\PINGQI~1\AppData\Local\Temp\go-build372864814\b056\_x012.o: In function `HMAC_CTX_new':
E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24346: undefined reference to `HMAC_CTX_init'
C:\Users\PINGQI~1\AppData\Local\Temp\go-build372864814\b056\_x012.o: In function `HMAC_CTX_free':
E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24358: undefined reference to `HMAC_CTX_cleanup'
E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24358: undefined reference to `HMAC_CTX_cleanup'
E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24358: undefined reference to `HMAC_CTX_cleanup'
collect2.exe: error: ld returned 1 exit status
```

The installation of `OpenSSL` version and the system environment variables have been checked on both machines and they are consistent.

`mingw64\include\openssl\opensslv.h` and `mingw64\x86_64-w64-mingw32\include\openssl\opensslv.h`
```
# define OPENSSL_VERSION_NUMBER  0x1010108fL
# define OPENSSL_VERSION_TEXT    "OpenSSL 1.1.1h  22 Sep 2020"
```

any clue?

**Comment by xeodou** [comment]
> I'm having a strange problem. I was able to get it installed and running on one PC, but on another PC I was experiencing the following error:
> 
> ```
> # github.com/xeodou/go-sqlcipher
> C:\Users\PINGQI~1\AppData\Local\Temp\go-build372864814\b056\_x012.o: In function `sqlcipher_openssl_deactivate':
> E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24452: undefined reference to `EVP_cleanup'
> C:\Users\PINGQI~1\AppData\Local\Temp\go-build372864814\b056\_x012.o: In function `sqlcipher_openssl_activate':
> E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24423: undefined reference to `OPENSSL_add_all_algorithms_noconf'
> C:\Users\PINGQI~1\AppData\Local\Temp\go-build372864814\b056\_x012.o: In function `HMAC_CTX_new':
> E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24346: undefined reference to `HMAC_CTX_init'
> C:\Users\PINGQI~1\AppData\Local\Temp\go-build372864814\b056\_x012.o: In function `HMAC_CTX_free':
> E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24358: undefined reference to `HMAC_CTX_cleanup'
> E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24358: undefined reference to `HMAC_CTX_cleanup'
> E:\data\Go\pkg\mod\github.com\xeodou\go-sqlcipher@v0.0.0-20200727080346-d681773ef093/sqlite3-binding.c:24358: undefined reference to `HMAC_CTX_cleanup'
> collect2.exe: error: ld returned 1 exit status
> ```
> 
> The installation of `OpenSSL` version and the system environment variables have been checked on both machines and they are consistent.
> 
> `mingw64\include\openssl\opensslv.h` and `mingw64\x86_64-w64-mingw32\include\openssl\opensslv.h`
> 
> ```
> # define OPENSSL_VERSION_NUMBER  0x1010108fL
> # define OPENSSL_VERSION_TEXT    "OpenSSL 1.1.1h  22 Sep 2020"
> ```
> 
> any clue?

This looks like the `libcrypto` is undefined for the library. Can you double you have the files in the right place?
Or you can build the library with the specific OpenSSL library for example,
```
CGO_ENABLE=1 CGO_LDFLAGS="-L/usr/local/opt/openssl/lib" CGO_CPPFLAGS="-I/usr/local/opt/openssl/include" go build _example/encrypto/encrypto.go

```

I don't own a Windows laptop anymore. I probably can make a test at the weekend using a virtual machine.

**Comment by navono** [comment]
@xeodou After going over the OpenSSL headers several times, found several OpenSSL headers in the x86 folder that were not replaced with the x64 version.
After replacing them, it works fine. Thanks again!
