### ISSUE TITLE
how to solver  openssl/rand.h  No such file or directory

### ISSUE THREAD

**Issue by sayyoume** [xeodou/go-sqlcipher#28]
sqlite3-binding.c:21629:10: fatal error: openssl/rand.h: No such file or directory

**Comment by xeodou** [comment]
@sayyoume  You need to install the OpenSSL as a dependency. If you are using windows, you can follow the instruction here https://github.com/xeodou/go-sqlcipher/wiki/Building#building-in-windows

**Comment by water160** [comment]
I solved it in Windows:
> 1、Download `MinGW`, I install [`CodeBlocks 20.03 with compiler`] which contains a MinGW compiler to simplify the installation of MinGW; The donwload link is [https://www.codeblocks.org/downloads/binaries/](https://www.codeblocks.org/downloads/binaries/)
(a) register `MinGW/bin` in the Windows System Environment `Path`, you can test this by open [PowerShell] and input `gcc -v` to check the version of gcc compiler;
(b) Assume the final installation path is `C:\Program Files\CodeBlocks\MinGW`

> 2、Download `OpenSSL`, the version is 3.0.15; The download link is [https://slproweb.com/products/Win32OpenSSL.html](https://slproweb.com/products/Win32OpenSSL.html)
(a) Assume the final installation path is `C:\Program Files\OpenSSL-Win64`

> 3、Copy 
    `C:\Program Files\OpenSSL-Win64\include\openssl`
to 
    `C:\Program Files\CodeBlocks\MinGW\x86_64-w64-mingw32\include`
or Make a symbol link
this step will add multiple openssl 'xxx.h' files to gcc; 

> 4、Copy 
    (1) `C:\Program Files\OpenSSL-Win64\lib\VC\x64\MD\libcrypto.def`
    (2) `C:\Program Files\OpenSSL-Win64\lib\VC\x64\MD\libcrypto.lib`
to 
    `C:\Program Files\CodeBlocks\MinGW\x86_64-w64-mingw32\lib\`
and change `libcrypto.lib` filename to `libcrypto.a`
this step will add the 'libcrypto' library to gcc; if not, you will get error info below when you execute command `go run xxx.go` or `go build xxx.go`:
[Error] C:/Program Files/CodeBlocks/MinGW/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: **cannot find -lcrypto**
