### ISSUE TITLE
warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated

### ISSUE THREAD

**Issue by nntaoli** [xeodou/go-sqlcipher#8]
warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here

**Comment by xeodou** [comment]
Upgrade to the latest version will fix the issue.
