### ISSUE TITLE
Update SQLCipher

### ISSUE THREAD

**Issue by gjrtimmer** [xeodou/go-sqlcipher#9]
@xeodou Can you to update it to the latest sqlite3 + SQLCipher ?

If not any information / howto on how to accomplish it ?

**Comment by xeodou** [comment]
@GJRTimmer  I can do it before the end of this week.

**Comment by gjrtimmer** [comment]
@xeodou That would be amazing, I'm trying for days now.

**Comment by gjrtimmer** [comment]
@xeodou will it only be SQLCipher or are you even going to attempt to take the latest go-sqlite3 from mattn

**Comment by xeodou** [comment]
@GJRTimmer  would be both. ;)

**Comment by gjrtimmer** [comment]
@xeodou Any luck yet ?

**Comment by xeodou** [comment]
@GJRTimmer  Upgrade with the latest sqlcipher & sqlite3 driver as well. The test pass as well.

**Comment by gjrtimmer** [comment]
@xeodou Thanks, really awesome, can you share on how you updated it ?
